apiVersion: v1
kind: ConfigMap
metadata:
  name: service-urls
data:
  RABBIT_URI: "amqp://rabbitmq-service:5672"
  BACKEND_API_URI: "localhost:3000"
  SOCKETIO_API_URI: "172.25.78.216:31677"
  PERSISTENCE_API_URI: "172.25.78.216:31496"
  MYSQL_DB_HOST: "mysql-service"
  MYSQL_DB_USER: "root"
  MYSQL_DB_PASSWORD: "1234"
  MYSQL_DB_PORT: "3306"
  MYSQL_DB_DATABASE: "inventariotraining"
  MONGO_DB_URI: "mongodb+srv://admin:admin@inventario.k32rhkn.mongodb.net/"
